### ISSUE TITLE
Possibility of a new sound notification?

### ISSUE THREAD

**Issue by Piyokopyo** [Chaser324/live-bomb#19]
Since all the sounds are GB related, I think it'd just be fitting to have (a small excerpt of the actual song part) of https://www.youtube.com/watch?v=qU71mFo0WXQ as a usable sound. It's a bit more vulgar than the others, but GB is all about being vulgar, isn't it? And I'd just laugh every time I hear it going off.

**Comment by lightsoda** [comment]
Up to @Chaser324, adding that would mean flagging it as Mature on the chrome web store.

[As the rating guideline states](https://developer.chrome.com/webstore/rating):

**Strong language**
Apps that contain explicit or frequent use of profanity should be rated "Mature.”

**Comment by Chaser324** [comment]
I'm personally not really in favor of it.

**Comment by Piyokopyo** [comment]
ah well, worth asking

**Comment by Chaser324** [comment]
Closing this issue, but I'm still open to suggestions for other new sound clips if they don't contain profanity.
