### ISSUE TITLE
Normalize notification sound files.

### ISSUE THREAD

**Issue by Chaser324** [Chaser324/live-bomb#22]
I've added a notification volume setting, but the volume of the sound files themselves need to be normalized to some extent to make setting the peak volume roughly consistent regardless of which sound clip is selected.

The *"Drop a bomb on it"* clip's volume is probably a pretty good baseline to balance the other clips around - bringing down the volume of the *Small Business Man* and raising the volume of the *GB Bumper* and *Rap Man* clips.

**Comment by Fattony12000** [comment]
I could do this for you, if you want.

**Comment by Chaser324** [comment]
@Fattony12000 - Feel free to do it. If you don't want to bother with git, you can just grab the audio files out of the `sounds` folder, modify them, and send them to me. I think they need to be `.ogg` format.

**Comment by Chaser324** [comment]
Fixed in pull request #23

**Comment by Fattony12000** [comment]
I fucked this up by not doing it properly. I'll do it properly if you want.

**Comment by Chaser324** [comment]
Sure. You can just submit a new pull request.
